// Code generated by protoc-gen-go. DO NOT EDIT.
// source: t_types.proto

package t_openr

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Object Operations.
type TObjectOp int32

const (
	// Reserved.
	TObjectOp_OP_RESERVED_OBJ TObjectOp = 0
	// Add.
	TObjectOp_OP_ADD_OBJ TObjectOp = 1
	// Update.
	TObjectOp_OP_UPDATE_OBJ TObjectOp = 2
	// Delete.
	TObjectOp_OP_DELETE_OBJ TObjectOp = 3
	// End of Object
	TObjectOp_OP_END_OBJ TObjectOp = 4
)

var TObjectOp_name = map[int32]string{
	0: "OP_RESERVED_OBJ",
	1: "OP_ADD_OBJ",
	2: "OP_UPDATE_OBJ",
	3: "OP_DELETE_OBJ",
	4: "OP_END_OBJ",
}
var TObjectOp_value = map[string]int32{
	"OP_RESERVED_OBJ": 0,
	"OP_ADD_OBJ":      1,
	"OP_UPDATE_OBJ":   2,
	"OP_DELETE_OBJ":   3,
	"OP_END_OBJ":      4,
}

func (x TObjectOp) String() string {
	return proto.EnumName(TObjectOp_name, int32(x))
}
func (TObjectOp) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_t_types_e506cb4c18ec1be6, []int{0}
}

type TAddrType int32

const (
	TAddrType_T_UNSPEC TAddrType = 0
	TAddrType_T_V4     TAddrType = 1
	TAddrType_T_V6     TAddrType = 2
)

var TAddrType_name = map[int32]string{
	0: "T_UNSPEC",
	1: "T_V4",
	2: "T_V6",
}
var TAddrType_value = map[string]int32{
	"T_UNSPEC": 0,
	"T_V4":     1,
	"T_V6":     2,
}

func (x TAddrType) String() string {
	return proto.EnumName(TAddrType_name, int32(x))
}
func (TAddrType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_t_types_e506cb4c18ec1be6, []int{1}
}

type TErrorStatus_TErrno int32

const (
	// No error occurs.
	TErrorStatus_SUCCESS TErrorStatus_TErrno = 0
	// Unknown version.
	TErrorStatus_UNKNOWN_VERSION TErrorStatus_TErrno = 1
	// Client is not connected.
	TErrorStatus_NOT_CONNECTED TErrorStatus_TErrno = 2
	// Connection is in use.
	TErrorStatus_ALREADY_INUSE TErrorStatus_TErrno = 3
	// Try again current operation.
	TErrorStatus_TRY_OPS_AGAIN TErrorStatus_TErrno = 4
	// Service is not available.
	TErrorStatus_NOT_AVAILABLE TErrorStatus_TErrno = 5
	// Wait for last request over.
	TErrorStatus_BUSY TErrorStatus_TErrno = 6
	// Invalid parameters.
	TErrorStatus_INVALID_PARAM TErrorStatus_TErrno = 7
	// Operation not supported.
	TErrorStatus_NOT_SUPPORTED TErrorStatus_TErrno = 8
	// Operation timeout.
	TErrorStatus_TIMEOUT TErrorStatus_TErrno = 9
	// Memory is unsufficient.
	TErrorStatus_NO_MEMORY TErrorStatus_TErrno = 10
	// General Error.
	TErrorStatus_GER_ERROR TErrorStatus_TErrno = 11
	// !!! Error codes for route operations.
	TErrorStatus_ERR_ROUTE_OFFSET TErrorStatus_TErrno = 4096
	// add route failed
	TErrorStatus_ERR_ROUTE_ADD TErrorStatus_TErrno = 4097
	// update route failed
	TErrorStatus_ERR_ROUTE_UPDT TErrorStatus_TErrno = 4098
	// delete route failed
	TErrorStatus_ERR_ROUTE_DEL TErrorStatus_TErrno = 4099
)

var TErrorStatus_TErrno_name = map[int32]string{
	0:    "SUCCESS",
	1:    "UNKNOWN_VERSION",
	2:    "NOT_CONNECTED",
	3:    "ALREADY_INUSE",
	4:    "TRY_OPS_AGAIN",
	5:    "NOT_AVAILABLE",
	6:    "BUSY",
	7:    "INVALID_PARAM",
	8:    "NOT_SUPPORTED",
	9:    "TIMEOUT",
	10:   "NO_MEMORY",
	11:   "GER_ERROR",
	4096: "ERR_ROUTE_OFFSET",
	4097: "ERR_ROUTE_ADD",
	4098: "ERR_ROUTE_UPDT",
	4099: "ERR_ROUTE_DEL",
}
var TErrorStatus_TErrno_value = map[string]int32{
	"SUCCESS":          0,
	"UNKNOWN_VERSION":  1,
	"NOT_CONNECTED":    2,
	"ALREADY_INUSE":    3,
	"TRY_OPS_AGAIN":    4,
	"NOT_AVAILABLE":    5,
	"BUSY":             6,
	"INVALID_PARAM":    7,
	"NOT_SUPPORTED":    8,
	"TIMEOUT":          9,
	"NO_MEMORY":        10,
	"GER_ERROR":        11,
	"ERR_ROUTE_OFFSET": 4096,
	"ERR_ROUTE_ADD":    4097,
	"ERR_ROUTE_UPDT":   4098,
	"ERR_ROUTE_DEL":    4099,
}

func (x TErrorStatus_TErrno) String() string {
	return proto.EnumName(TErrorStatus_TErrno_name, int32(x))
}
func (TErrorStatus_TErrno) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_t_types_e506cb4c18ec1be6, []int{1, 0}
}

type TInitMsg struct {
	// major version,
	MajorVersion uint32 `protobuf:"varint,1,opt,name=majorVersion,proto3" json:"majorVersion,omitempty"`
	// minor version
	MinorVersion         uint32   `protobuf:"varint,2,opt,name=minorVersion,proto3" json:"minorVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TInitMsg) Reset()         { *m = TInitMsg{} }
func (m *TInitMsg) String() string { return proto.CompactTextString(m) }
func (*TInitMsg) ProtoMessage()    {}
func (*TInitMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_types_e506cb4c18ec1be6, []int{0}
}
func (m *TInitMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TInitMsg.Unmarshal(m, b)
}
func (m *TInitMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TInitMsg.Marshal(b, m, deterministic)
}
func (dst *TInitMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TInitMsg.Merge(dst, src)
}
func (m *TInitMsg) XXX_Size() int {
	return xxx_messageInfo_TInitMsg.Size(m)
}
func (m *TInitMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_TInitMsg.DiscardUnknown(m)
}

var xxx_messageInfo_TInitMsg proto.InternalMessageInfo

func (m *TInitMsg) GetMajorVersion() uint32 {
	if m != nil {
		return m.MajorVersion
	}
	return 0
}

func (m *TInitMsg) GetMinorVersion() uint32 {
	if m != nil {
		return m.MinorVersion
	}
	return 0
}

type TErrorStatus struct {
	Status               TErrorStatus_TErrno `protobuf:"varint,1,opt,name=Status,proto3,enum=t_openr.TErrorStatus_TErrno" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TErrorStatus) Reset()         { *m = TErrorStatus{} }
func (m *TErrorStatus) String() string { return proto.CompactTextString(m) }
func (*TErrorStatus) ProtoMessage()    {}
func (*TErrorStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_types_e506cb4c18ec1be6, []int{1}
}
func (m *TErrorStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TErrorStatus.Unmarshal(m, b)
}
func (m *TErrorStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TErrorStatus.Marshal(b, m, deterministic)
}
func (dst *TErrorStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TErrorStatus.Merge(dst, src)
}
func (m *TErrorStatus) XXX_Size() int {
	return xxx_messageInfo_TErrorStatus.Size(m)
}
func (m *TErrorStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_TErrorStatus.DiscardUnknown(m)
}

var xxx_messageInfo_TErrorStatus proto.InternalMessageInfo

func (m *TErrorStatus) GetStatus() TErrorStatus_TErrno {
	if m != nil {
		return m.Status
	}
	return TErrorStatus_SUCCESS
}

type TAddress struct {
	Type                 TAddrType `protobuf:"varint,1,opt,name=type,proto3,enum=t_openr.TAddrType" json:"type,omitempty"`
	Address              string    `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TAddress) Reset()         { *m = TAddress{} }
func (m *TAddress) String() string { return proto.CompactTextString(m) }
func (*TAddress) ProtoMessage()    {}
func (*TAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_types_e506cb4c18ec1be6, []int{2}
}
func (m *TAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TAddress.Unmarshal(m, b)
}
func (m *TAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TAddress.Marshal(b, m, deterministic)
}
func (dst *TAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TAddress.Merge(dst, src)
}
func (m *TAddress) XXX_Size() int {
	return xxx_messageInfo_TAddress.Size(m)
}
func (m *TAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_TAddress.DiscardUnknown(m)
}

var xxx_messageInfo_TAddress proto.InternalMessageInfo

func (m *TAddress) GetType() TAddrType {
	if m != nil {
		return m.Type
	}
	return TAddrType_T_UNSPEC
}

func (m *TAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*TInitMsg)(nil), "t_openr.TInitMsg")
	proto.RegisterType((*TErrorStatus)(nil), "t_openr.TErrorStatus")
	proto.RegisterType((*TAddress)(nil), "t_openr.TAddress")
	proto.RegisterEnum("t_openr.TObjectOp", TObjectOp_name, TObjectOp_value)
	proto.RegisterEnum("t_openr.TAddrType", TAddrType_name, TAddrType_value)
	proto.RegisterEnum("t_openr.TErrorStatus_TErrno", TErrorStatus_TErrno_name, TErrorStatus_TErrno_value)
}

func init() { proto.RegisterFile("t_types.proto", fileDescriptor_t_types_e506cb4c18ec1be6) }

var fileDescriptor_t_types_e506cb4c18ec1be6 = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0xdb, 0xae, 0xf4, 0xcf, 0xbb, 0xb6, 0x18, 0x4f, 0x48, 0x3b, 0x70, 0xa8, 0x7a, 0x40,
	0x68, 0x12, 0x3d, 0xc0, 0xc4, 0xdd, 0x6d, 0xde, 0x4d, 0x19, 0xa9, 0x6d, 0xbd, 0x76, 0x82, 0x7a,
	0xb2, 0x3a, 0x16, 0x50, 0x27, 0xd1, 0x54, 0x49, 0x38, 0xec, 0xc6, 0x9f, 0xcf, 0xc2, 0xb7, 0xe3,
	0x43, 0x20, 0x27, 0x29, 0x1d, 0xdc, 0xfc, 0x3e, 0xfe, 0x3d, 0xf1, 0x93, 0xc7, 0x86, 0x71, 0xe9,
	0xca, 0x87, 0x7d, 0x5a, 0xcc, 0xf7, 0x79, 0x56, 0x66, 0xbc, 0x5f, 0xba, 0x6c, 0x9f, 0xee, 0xf2,
	0x19, 0xc1, 0xc0, 0x86, 0xbb, 0x6d, 0xb9, 0x2a, 0x3e, 0xf3, 0x19, 0x8c, 0xbe, 0x6c, 0xee, 0xb3,
	0x3c, 0x49, 0xf3, 0x62, 0x9b, 0xed, 0xce, 0xdb, 0xd3, 0xf6, 0xab, 0x31, 0xfd, 0xa3, 0x55, 0xcc,
	0x76, 0x77, 0x64, 0x3a, 0x0d, 0xf3, 0x48, 0x9b, 0xfd, 0xee, 0xc0, 0xc8, 0x62, 0x9e, 0x67, 0xb9,
	0x29, 0x37, 0xe5, 0xd7, 0x82, 0x5f, 0x42, 0xaf, 0x5e, 0x55, 0x9f, 0x9c, 0xbc, 0x79, 0x31, 0x6f,
	0x8e, 0x9f, 0x3f, 0xc6, 0xaa, 0x61, 0x97, 0x51, 0xc3, 0xce, 0x7e, 0x75, 0xa0, 0x57, 0x4b, 0xfc,
	0x14, 0xfa, 0x26, 0x5e, 0x2e, 0xd1, 0x18, 0xd6, 0xe2, 0x67, 0xf0, 0x34, 0x96, 0xef, 0xa5, 0xfa,
	0x20, 0x5d, 0x82, 0x64, 0x42, 0x25, 0x59, 0x9b, 0x3f, 0x83, 0xb1, 0x54, 0xd6, 0x2d, 0x95, 0x94,
	0xb8, 0xb4, 0x18, 0xb0, 0x8e, 0x97, 0x44, 0x44, 0x28, 0x82, 0xb5, 0x0b, 0x65, 0x6c, 0x90, 0x9d,
	0x78, 0xc9, 0xd2, 0xda, 0x29, 0x6d, 0x9c, 0xb8, 0x16, 0xa1, 0x64, 0xdd, 0x83, 0x51, 0x24, 0x22,
	0x8c, 0xc4, 0x22, 0x42, 0xf6, 0x84, 0x0f, 0xa0, 0xbb, 0x88, 0xcd, 0x9a, 0xf5, 0xfc, 0x66, 0x28,
	0x13, 0x11, 0x85, 0x81, 0xd3, 0x82, 0xc4, 0x8a, 0xf5, 0x0f, 0xbc, 0x89, 0xb5, 0x56, 0xe4, 0x0f,
	0x1a, 0xf8, 0x74, 0x36, 0x5c, 0xa1, 0x8a, 0x2d, 0x1b, 0xf2, 0x31, 0x0c, 0xa5, 0x72, 0x2b, 0x5c,
	0x29, 0x5a, 0x33, 0xf0, 0xe3, 0x35, 0x92, 0x43, 0x22, 0x45, 0xec, 0x94, 0x3f, 0x07, 0x86, 0x44,
	0x8e, 0x54, 0x6c, 0xd1, 0xa9, 0xab, 0x2b, 0x83, 0x96, 0x7d, 0x9b, 0x72, 0x0e, 0xe3, 0xa3, 0x2c,
	0x82, 0x80, 0x7d, 0x9f, 0xf2, 0x33, 0x98, 0x1c, 0xb5, 0x58, 0x07, 0x96, 0xfd, 0xf8, 0x0f, 0x0c,
	0x30, 0x62, 0x3f, 0xa7, 0xb3, 0x08, 0x06, 0x56, 0xdc, 0xdd, 0xe5, 0x69, 0x51, 0xf0, 0x97, 0xd0,
	0xf5, 0xd7, 0xdc, 0xf4, 0xcc, 0x8f, 0x3d, 0x7b, 0xc0, 0x3e, 0xec, 0x53, 0xaa, 0xf6, 0xf9, 0x39,
	0xf4, 0x37, 0xb5, 0xa5, 0xba, 0xc1, 0x21, 0x1d, 0xc6, 0x8b, 0x4f, 0x30, 0xb4, 0xea, 0xf6, 0x3e,
	0xfd, 0x58, 0xaa, 0xbd, 0xaf, 0x5a, 0x69, 0x47, 0x68, 0x90, 0x12, 0x0c, 0x9c, 0x5a, 0xdc, 0xb0,
	0x16, 0x9f, 0x00, 0x28, 0xed, 0x53, 0x56, 0x73, 0x55, 0xbd, 0xd2, 0x3e, 0xa1, 0xf0, 0xff, 0xb4,
	0xb8, 0xa9, 0xab, 0x57, 0xda, 0xe7, 0xc3, 0x46, 0x3a, 0x69, 0x5c, 0x28, 0x6b, 0x57, 0xf7, 0xe2,
	0x35, 0x0c, 0xff, 0x86, 0xe2, 0x23, 0x18, 0x58, 0x17, 0x4b, 0xa3, 0x71, 0xc9, 0x5a, 0xbe, 0x7f,
	0xeb, 0x92, 0x4b, 0xd6, 0x6e, 0x56, 0xef, 0x58, 0xe7, 0xb6, 0x57, 0xbd, 0xdb, 0xb7, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xbf, 0x85, 0x99, 0xbb, 0xc8, 0x02, 0x00, 0x00,
}
